apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "text-summarization.fullname" . }}-netpol
  labels:
    {{- include "text-summarization.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "text-summarization.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
    - podSelector:
        matchLabels:
          app: istio-proxy
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8000
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS outbound for AI API calls
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP to auth service and other internal services
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 8080
