{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "text-summarization.fullname" . }}-pdb
  labels:
    {{- include "text-summarization.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "text-summarization.selectorLabels" . | nindent 6 }}
{{- end }}
