apiVersion: v1
kind: Service
metadata:
  name: {{ include "text-summarization.fullname" . }}
  labels:
    {{- include "text-summarization.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "text-summarization.selectorLabels" . | nindent 4 }}
