{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "text-summarization.serviceAccountName" . }}
  labels:
    {{- include "text-summarization.labels" . | nindent 4 }}
  {{- if .Values.vault.enabled }}
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "{{ .Values.vault.agent.role }}"
  {{- end }}
{{- end }}
