global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # "first_rules.yml"
  # "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'text-summarization'
    static_configs:
      - targets: ['text-summarization:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
  
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
    scrape_interval: 15s
    scheme: http

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
