apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgresql-network-policy
  namespace: mcp-poc
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-mcp
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: postgresql-mcp
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow access from context-service
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: context-service
    ports:
    - protocol: TCP
      port: 5432
  # Allow access from auth-service
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: auth-service
    ports:
    - protocol: TCP
      port: 5432
  # Allow access from pods with specific service accounts
  - from:
    - podSelector:
        matchLabels:
          serviceAccount: context-service
    ports:
    - protocol: TCP
      port: 5432
  - from:
    - podSelector:
        matchLabels:
          serviceAccount: auth-service
    ports:
    - protocol: TCP
      port: 5432
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow outbound HTTPS for cert-manager
  - to: []
    ports:
    - protocol: TCP
      port: 443
